cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

lint:
  stage: test
  tags:
  - nodejs
  script:
  - npm run lint

audit:
  stage: test
  tags:
  - nodejs
  script:
  - npm audit

