exchange_settings:
  use_cache: True # Put to False in production
  apiKey: "" # Alpha Vantage API Key
 
telegram_settings:
  bot_token: "" # Telegram token you receive from @BotFather
  public_url: "https://" # Telegram public URL for Webhook
  chat_id: "@" # Telegram chat ID to send to (eg. @channel_name)
  
tickers:
  volatility:
    params:
      symbol: "VIX" # The VIX Index
      function: "TIME_SERIES_INTRADAY" # Intraday time series (within a day period, see intraday_interval)
      # Note: NYSE market: 6,5 hours open = 390 min./5 min. interval = 78 data points (which will fit within the 100 latest data points)
      intraday_interval: "5min" # Other options are: 1min, 5min, 15min, 30min, 60min
      outputsize: "compact" # Default: compact (100 latest data points), full (get the full-length of 20+ years historical data)
    cron_time: "0 15 12,16 * * 1-5" # Notation: Second-Minute-Hour-Day-Month-WeekDay. So, at 12:15:00 and 16:15:00 hours from Monday through Friday
    cron_timezone: "America/New_York" # NYSE is in New York
    alerts: # Note: Lower checks on <, higher checks on >=
      extreme_low_threshold: 8 # VIX index is < 8%
      low_threshold: 11 # VIX index is < 11%
      high_threshold: 40 # VIX index is >= 40%
      extreme_high_threshold: 60 # VIX index is >= 60%
  stockmarket:
    params:
      symbol: "GSPC" # The GSPC Index
      function: "TIME_SERIES_WEEKLY" # Weekly time series
    cron_time: "*/5 * * * * *" # Notation: Second-Minute-Hour-Day-Month-WeekDay. So, at 12:15:00 and 16:15:00 hours from Monday through Friday
    cron_timezone: "America/New_York" # NYSE is in New York
    warmup_period: 26 # Longest moving average period (before PPO gets used)
    indicators:
      PPO:
        short: 12 # Short EMA period of 12
        long: 26 # Long EMA period of 26
        signal: 9 # Signal period of 9

