exchange_settings:
  use_cache: True # Put to False in production
  apiKey: "" # Twelve Data Key
 
telegram_settings:
  bot_token: "" # Telegram token you receive from @BotFather: 1104044500:AAEt0CI4_ZneVx2RJQXlFFfmaWYBW5EYMdA
  public_url: "https://" # Telegram public URL for Webhook
  chat_id: "@" # Telegram chat ID to send to (eg. @channel_name)
  
tickers:
  volatility:
    params:
      symbol: "VIX" # The CBOE Volatility Index
      interval: "5min" # Intraday time series of 5 min. interval (within a day period, see intraday_interval)
      outputsize: 100
      # Note: NYSE market: 6,5 hours open = 390 min./5 min. interval = 78 data points (which will fit within the 100 latest data points)
    cron_time: "0 15 12,16 * * 1-5" # Notation: Second-Minute-Hour-Day-Month-WeekDay. So, at 12:15:00 and 16:15:00 hours from Monday through Friday    
    cron_timezone: "America/New_York" # NYSE is in New York
    # Extra data for volatility check
    alerts: # Note: Lower checks on <, higher checks on >=
      extreme_low_threshold: 8 # VIX index is < 8%
      low_threshold: 11 # VIX index is < 11%
      high_threshold: 40 # VIX index is >= 40%
      extreme_high_threshold: 60 # VIX index is >= 60%
  stockmarket:
    params:
      symbol: "GSPC" # The S&P 500 Index
      interval: "1week" # Weekly time series
      outputsize: 100
    cron_time: "0 20 16 * * 5" # Notation: Second-Minute-Hour-Day-Month-WeekDay. So, at every Friday at 16:20:00 hours (when market is closed)
    cron_timezone: "America/New_York" # NYSE is in New York
    # Extra data for stock market check
    indicators:
      PPO:
        short: 12 # Short EMA period of 12
        long: 26 # Long EMA period of 26
        signal: 9 # Signal period of 9
    warmup_period: 30 # Longest moving average period + extra slack (before PPO will be used)
    data_period: 20 # Fetch some additional time period (after warm-up), which will be used to be actually analysed
