exchange_settings:
  use_cache: True # Put to False in production
  api_token: "" # TwelveData API Token
 
telegram_settings:
  bot_token: "" # Telegram token you receive from @BotFather
  public_url: "https://" # Telegram public URL for Webhook
  chat_id: "@" # Telegram chat ID to send to (eg. @channel_name)
  
tickers:
  params:
    crypto_symbols_pairs: [ "BTC/USD", "ETH/USD", "BNB/USD", "ADA/USD", "LINK/USD", "SOL/USD", "pDOTn/USD" ]
    exchange: "Binance" # Default timezone for Binance data is UTC (Coordinated Universal Time)
    interval: "1week"
    outputsize: 100
  cron_time: "0 0 11,16 * * *" # Notation: Second-Minute-Hour-Day-Month-WeekDay. So, every day at 11:00 UTC and 16:00 UTC
  # Extra settings for crypto checks
  indicators:
    PPO:
      short: 12 # Short EMA period of 12
      long: 26 # Long EMA period of 26
      signal: 9 # Signal period of 9
  warmup_period: 30 # Longest moving average period + extra slack (before PPO will be used)
  data_period: 20 # Fetch some additional time period (after warm-up), which will be used to be actually analysed
