general_settings:
  verbose: false # Enable debug logging to stdout?
  dumpCSV: false # Dump data procesing data to CSV file?

exchange_settings:
  use_cache: True # Put to False in production
  api_token: "" # TwelveData API Token
 
telegram_settings:
  bot_token: "" # Telegram token you receive from @BotFather
  public_url: "https://" # Telegram public URL for Webhook
  chat_id: "@" # Telegram chat ID to send to (eg. @channel_name)
  
tickers:
  params:
    # Optionally you could provide the crypto exchange like so: BTC/USD:Huobi
    crypto_symbols_pairs: [ "BTC/USD", "ETH/USD", "ADA/USD", "LINK/USD", "SOL/USD", "pDOTn/USD", "MATIC/USD", "ALGO/USD", "AVAX/USD", "VET/USD" ]
    interval: "1week"
    outputsize: 100
  cron_time: "0 15 * * * *" # Notation: Second-Minute-Hour-Day-Month-WeekDay. So, every hour at hh:15 hour, since crypto can be volatile. Keep the time between cron triggers above 10 mins to avoid API rate limit issues.
  cron_timezone: "Europe/Amsterdam" # Your local time
  # Extra settings for crypto checks
  indicators:
    PPO:
      short: 12 # Short EMA period of 12
      long: 26 # Long EMA period of 26
      signal: 9 # Signal period of 9
  warmup_period: 30 # Longest moving average period + extra slack (before PPO will be used)
  data_period: 20 # Fetch some additional time period (after warm-up), which will be used to be actually analysed
