version: "3"
services:
  crypto_bot:
    image: danger89/crypto-bot:latest
    container_name: crypto_bot
    restart: always
    volumes:
      - /home/username/folder/to/config.yml:/app/config.yml
    ports:
      - "3010:3010"
