version: "3"
services:
  crypto-bot:
    image: danger89/crypto-bot:latest
    container_name: crypto-bot
    restart: always
    volumes:
      - /home/username/folder/to/config.yml:/app/config.yml
      - /home/username/folder/to/tmp:/app/tmp
    ports:
      - "3010:3010"
