services:
  crypto-bot:
    image: registry.melroy.org/melroy/crypto-bot/crypto-bot:latest
    container_name: crypto-bot
    restart: always
    networks:
      - crypto_bot_external_network
    volumes:
      - /home/username/folder/to/config.yml:/app/config.yml:ro
      - /home/username/folder/to/tmp:/app/tmp
    ports:
      - "127.0.0.1:3010:3010"

networks:
  crypto_bot_external_network:
